Description: >
  Tarun Kumar Udacity Cloud Devops Capstone Project / Create EC2 Instances
  
Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Default: CapstoneProject
    Type: String
  SSHKeyName:
    Description: SSH key for management access
    Default: udacity
    Type: String
  ImageId:
    Description: Defines the Image-ID of the OS to deploy
    Default: ami-02fe94dee086c0c37
    Type: String

Resources:

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub ${EnvironmentName}-ec2-SecG
      GroupDescription: Allow port 22 for management
      #VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ec2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref ImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2-instance1
        - Key: Project6
          Value: !Ref EnvironmentName

  ec2Instance2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: !Ref SSHKeyName
      ImageId: !Ref ImageId
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-ec2-instance2
        - Key: Project6
          Value: !Ref EnvironmentName