version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
  
parameters:
  workflow-id:
    type: string
    default: "${CIRCLE_WORKFLOW_ID:0:7}"

jobs:
    run-lint:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
              sudo chmod +x /bin/hadolint
        - run:
            name: Run Lint
            command: |
              hadolint Dockerfile
    build-docker-image:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout

        - setup_remote_docker:
            version: 19.03.13

        - run:
            name: Build Docker Image
            command: |
              export TAG=v${CIRCLE_BUILD_NUM}
              export IMAGE_NAME=capstone
              docker build -t kumatrx/$IMAGE_NAME:$TAG .
    push-docker-image:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - setup_remote_docker:
            version: 19.03.13
        - run:
            name: Push Docker Image to Docker Hub
            command: |
              export TAG=v${CIRCLE_BUILD_NUM}
              export IMAGE_NAME=capstone
              docker build -t kumatrx/$IMAGE_NAME:$TAG .
              docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
              docker push kumatrx/$IMAGE_NAME:$TAG

workflows:
  default:
    jobs:
      - run-lint
      - build-docker-image:
          requires:
            - "run-lint"
      - push-docker-image:
          requires:
            - "build-docker-image"
      - aws-ecr/build_and_push_image:
          name: build-and-push-image-ecr
          account-url: ${AWS_ECR_ACCOUNT_URL}
          region: ${AWS_DEFAULT_REGION}
          repo: ${AWS_REPONAME}
          dockerfile: ~/project/Dockerfile
          path: ~/project/
          tag: ${CIRCLE_SHA1}